# Generated by Django 6.0.4 on 2026-05-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='default.png', upload_to='productos'),
        ),
    ]
